name: 'Acción de repetición'
author: 'Guillermo'
description: 'Repite un número de veces el texto indicado'

inputs:
  input_text:
    description: 'El texto que queremos repetir varias veces'
    required: true
  num_of_repeats:
    description: 'Número de veces que queremos que aparezca el texto'
    required: false
    default: '1'

outputs:
  output_text:
    description: 'El texto repetido el número de veces indicado'

# Aquí van los valores específicos para configurar Docker 
# o JavaScript, se explicarán más adelante.

branding:
  icon: 'rotate-cw'
  color: 'blue'